- name: HTML
  logo: html5
  url: https://github.com/sarthaktexas?tab=repositories&q=&type=&language=html
  color: E34F26
  projects:
    - https://github.com/sarthaktexas/ScienceBowlScoreTimer
    - https://github.com/sarthaktexas/waves
- name: JavaScript
  logo: javascript
  url: https://github.com/sarthaktexas?tab=repositories&q=&type=&language=javascript
  color: F1E05A
  projects:
    - https://github.com/sarthaktexas/website
    - https://github.com/sarthakmohantyinc/Opes
    - https://github.com/sarthaktexas/zoom-dashboard
    - https://github.com/sarthakmohantyinc/Labori
    - https://github.com/sarthaktexas/salamandarian
    - https://github.com/sarthaktexas/ocean-architecture
    - https://github.com/sarthaktexas/discord-user-bot
    - https://github.com/sarthaktexas/send-message-serverless
    - https://github.com/sarthaktexas/home-automation-serverless
    - https://github.com/sarthaktexas/kick-talking-user-discord-bot
    - https://github.com/sarthaktexas/kosmos-discord-music-bot
    - https://github.com/sarthaktexas/srtk.me
    - https://github.com/sarthaktexas/adventofcode2020
    - https://github.com/sarthaktexas/secret-santa-pairing
    - https://github.com/sarthaktexas/og-cards
- name: Next.js
  logo: next.js
  url: https://github.com/sarthaktexas?tab=repositories&q=&type=&language=javascript
  color: '000000'
  projects:
    - https://github.com/sarthaktexas/website-v2
    - https://github.com/sarthaktexas/srtk.me-v2
    - https://github.com/sarthaktexas/notes
    - https://github.com/sarthaktexas/website-v3
    - https://github.com/sarthaktexas/anomaly-science
    - https://github.com/sarthaktexas/claire-website
    - https://github.com/sarthaktexas/swirlbrand
    - https://github.com/sarthaktexas/hackathon-site-template
    - https://github.com/sarthaktexas/perfect
    - https://github.com/thinkfiveable/open
- name: Swift
  logo: swift
  url: https://github.com/sarthaktexas?tab=repositories&q=&type=&language=swift
  color: FA7343
  projects:
    - https://github.com/HackClub/Rudolph
- name: Python
  logo: python
  url: https://github.com/sarthaktexas?tab=repositories&q=&type=&language=python
  color: 3776AB
  projects:
    - url: https://github.com/sarthaktexas/kahootbot
